spring.application.name=demo

server.port=8080
server.address=0.0.0.0

spring.datasource.url=${DATABASE_URL}

spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# The format used for the keystore. It could be set to JKS in case it is a JKS file
#server.ssl.key-store-type=PKCS12

# The path to the keystore containing the certificate
#server.ssl.key-store=classpath:./localhost.p12

# The password used to generate the certificate
#server.ssl.key-store-password=password

# The alias mapped to the certificate
#server.ssl.key-alias=localhost

#server.ssl.enabled=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
server.forward-headers-strategy=framework


# server.ssl.enabled=false
# server.servlet.session.cookie.secure=false
# server.servlet.session.cookie.same-site=lax
